version: "3.8"

services:
  web:
    build: ./fastapi-app
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: mongodb://mongo:27017
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:6.0.24
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
