services:
  fastapi:
    build:
      context: ./fastapi-app
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: mongodb://mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
