name: Build, Test, and Dispatch Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t mdapkr-fastapi:test ./fastapi-app

  unit-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and run unit tests
        run: |
          pip install pytest
          pytest tests/unit

  e2e-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pytest requests

      - name: Start Docker Compose services
        run: docker compose -f docker-compose.test.yml up -d

      - name: Wait for API to be healthy
        run: |
          for i in {1..10}; do
            curl -s http://localhost:8000/people && exit 0 || sleep 3
          done
          echo "API did not start in time" && exit 1

      - name: Run E2E tests
        run: pytest tests/e2e

      - name: Stop Docker Compose services
        run: docker compose -f docker-compose.test.yml down

  push-to-ecr:
    runs-on: ubuntu-latest
    needs: [unit-test, e2e-test]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::055029294053:role/GitHubActionsECRPush
          aws-region: ap-south-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and push Docker image to ECR
        env:
          ECR_REGISTRY: 055029294053.dkr.ecr.ap-south-1.amazonaws.com
          ECR_REPOSITORY: mdapkr-fastapi
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag mdapkr-fastapi:test $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Clean up local Docker images
        run: |
          docker rmi mdapkr-fastapi:test || true
          docker rmi $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG || true
          docker image prune -f

  deploy:
    runs-on: ubuntu-latest
    needs: push-to-ecr

    steps:
      - name: Trigger CD workflow in mdapkr-k8s repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CD_TRIGGER_PAT }}
          repository: tamirkafridjerassi/mdapkr-k8s
          event-type: deploy-mdapkr
          client-payload: '{"image_tag": "${{ github.sha }}"}'
