services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: mongodb://mongo:27017
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:6.0.12
    expose:
      - 27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
